# Generated by Django 3.2.13 on 2022-07-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220726_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductId',
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
