# Generated by Django 3.2.13 on 2022-07-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220727_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='product_name',
        ),
        migrations.AddField(
            model_name='catalog',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
