# Generated by Django 3.2.13 on 2022-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220727_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='code',
        ),
    ]
