# Generated by Django 3.2.13 on 2022-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_catalog_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
