# Generated by Django 3.2.13 on 2022-07-28 11:35

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(related_name='_main_category_sub_categories_+', to='main.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abc1234', length=5, max_length=40, prefix='code_'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='main.Category'),
        ),
    ]
